/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/caption": {
    post: operations["CaptionController_create"];
    get: operations["CaptionController_getRandom"];
  };
}

export interface operations {
  CaptionController_create: {
    parameters: {};
    requestBody: {
      "application/json": components["schemas"]["CreateCaptionDto"];
    };
    responses: {
      "201": {
        "application/json": components["schemas"]["Caption"];
      };
    };
  };
  CaptionController_getRandom: {
    parameters: {
      query: {
        type: "male" | "female" | "both";
      };
    };
    responses: {
      "200": {
        "application/json": components["schemas"]["Caption"];
      };
    };
  };
}

export interface components {
  schemas: {
    CreateCaptionDto: { quote: string; type: "male" | "female" | "both" };
    Caption: {
      id: string;
      quote: string;
      createdAt: string;
      type: "male" | "female" | "both";
    };
  };
}
